# 5CS037 - Concepts and Technologies of AI.

Worksheet - 1: A coding exercises on Numpy.

In [1]:
import numpy as np

# 4.1
# Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.  
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [2]:
empty = np.empty((2,2)) # Empty array of shape (2,2)
ones = np.ones((4,2)) # Array filled with 1 of shape (2,2)
filled = np.full((2,2), 5)  # Array filled with 5 of shape (2,2)
zeros_like = np.zeros_like(filled) # Converts filled array into array containing 0
ones_like = np.ones_like(filled) # Converts filled array into array containing 1

new_list = [1, 2, 3, 4]
list_to_arr = np.array(new_list) # Converts python list to numpy array

print(f"Empty array :\n{empty}")
print(f"Ones array :\n{ones}")
print(f"5 Filled array :\n {filled}")
print(f"Zeros like array :\n {zeros_like}")
print(f"Ones like array :\n {ones_like}")
print(f"python list : {new_list} => type : {type(new_list)}\nTo numpy array : {list_to_arr} => type : {type(list_to_arr)}")

Empty array :
[[5.03402283e-310 0.00000000e+000]
 [3.45845952e-323             nan]]
Ones array :
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
5 Filled array :
 [[5 5]
 [5 5]]
Zeros like array :
 [[0 0]
 [0 0]]
Ones like array :
 [[1 1]
 [1 1]]
python list : [1, 2, 3, 4] => type : <class 'list'>
To numpy array : [1 2 3 4] => type : <class 'numpy.ndarray'>




---

# 4.1.1
Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [3]:
aranged_arr = np.arange(10, 49)
reshape_mat0_8 = np.arange(0,9).reshape(3,3)
identity3 = np.eye(3)
average_random = np.random.random(30).mean()
array_10_10 = np.random.random(100).reshape(10, 10)
min_value, max_value = array_10_10.min(), array_10_10.max()
zero_10 = np.zeros(10)
zero_10[4] = 5
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
array_2d = np.ones((6,6))
array_2d[1:-1, 1:-1] = 0
checkerboard = np.full((8,8), 'O')
checkerboard[1::2, ::2] = 'X'
checkerboard[::2, 1::2] = 'X'


print(f'Array of Values ranging from 10 to 49 : \n {aranged_arr}\n')
print(f'3X3 matrix with values ranging from 0 to 8 : \n {reshape_mat0_8}\n')
print(f'3X3 Identity matrix : \n {identity3}\n')
print(f'Average of random array of size 30 : \n{average_random}\n')
print(f'Minimum and Maximum of 10X10 array with random values : \nMin : {min_value:.2f}, Max : {max_value:.2f}\n')
print(f'Zero array of size 10 where 5th element replaced with 1 : \n{zero_10}\n')
print(f'Reversed array of {arr} : \n{reversed_arr}\n')
print(f'2d array of zeros with 1 in border : \n{array_2d}\n')
print(f'8X8 Matrix with checkerboard pattern : \n{checkerboard}\n')

Array of Values ranging from 10 to 49 : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

3X3 matrix with values ranging from 0 to 8 : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3X3 Identity matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Average of random array of size 30 : 
0.4628116765856738

Minimum and Maximum of 10X10 array with random values : 
Min : 0.01, Max : 0.99

Zero array of size 10 where 5th element replaced with 1 : 
[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]

Reversed array of [1, 2, 0, 0, 4, 0] : 
[0, 4, 0, 0, 2, 1]

2d array of zeros with 1 in border : 
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

8X8 Matrix with checkerboard pattern : 
[['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' '

---
Problem - 3: Array Operations:  
For the following arrays:  
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);  
v = np.array([9,10]) and w = np.array([11,12]);  
Complete all the task using numpy:  
1. Add the two array.  
2. Subtract the two array.  
3. Multiply the array with any integers of your choice.  
4. Find the square of each element of the array.  
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.  
6. Concatenate x(and)y along row and Concatenate v(and)w along column.  
{Hint:try np.concatenate() or np.vstack() functions.}  
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?  

In [4]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

sum_x_y = x + y
sum_v_w = v + w

diff_x_y = x - y
diff_v_w = v - w

scalar_x_11 = x * 11

x_squared = np.square(x)

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

concat_x_y = np.concatenate((x, y), axis=1)
concat_v_w = np.vstack((v,w))

# concat_x_v = np.concatenate((x, v), axis=1)
# ValueError: all the input arrays must have same number of dimensions, but the array at index 0 (x) has 2 dimensions and the array at index 1 (v) has 1 dimension

print(f' Matrix X :\n{x}\nMatrix Y :\n{y}\nMatrix V :\n{v}\nMatrix W :\n{w}\n')
print(f'Sum of X and Y : \n{sum_x_y}\n')
print(f'Sum of V and W : \n{sum_v_w}\n')
print(f'Difference of X and Y : \n{diff_x_y}\n')
print(f'Difference of V and W : \n{diff_v_w}\n')
print(f'Scalar multiplication of X with 11 : \n{scalar_x_11}\n')
print(f'Dot product of X and Y : \n{dot_x_y}\n')
print(f'Dot product of X and V : \n{dot_x_v}\n')
print(f'Dot product of V and W : \n{dot_v_w}\n')
print(f'Concatenation of X and Y along row : \n{concat_x_y}\n')
print(f'Concatenation of V and W along column : \n{concat_v_w}\n')
print(f'Concatenation of X and V is ValueError. The reason is shape incompatibility. Shape of : \nX is {x.shape} and\nV is {v.shape}')

 Matrix X :
[[1 2]
 [3 5]]
Matrix Y :
[[5 6]
 [7 8]]
Matrix V :
[ 9 10]
Matrix W :
[11 12]

Sum of X and Y : 
[[ 6  8]
 [10 13]]

Sum of V and W : 
[20 22]

Difference of X and Y : 
[[-4 -4]
 [-4 -3]]

Difference of V and W : 
[-2 -2]

Scalar multiplication of X with 11 : 
[[11 22]
 [33 55]]

Dot product of X and Y : 
[[19 22]
 [50 58]]

Dot product of X and V : 
[29 77]

Dot product of V and W : 
219

Concatenation of X and Y along row : 
[[1 2 5 6]
 [3 5 7 8]]

Concatenation of V and W along column : 
[[ 9 10]
 [11 12]]

Concatenation of X and V is ValueError. The reason is shape incompatibility. Shape of : 
X is (2, 2) and
V is (2,)


---
Problem - 4: Matrix Operations:
• For the following arrays:  
A = np.array([[3,4],[7,8]])  
B = np.array([[5,3],[2,1]]);  
Prove following with Numpy:  
1. Prove A.A−1 = I.  
2. Prove AB ̸= BA.  
3. Prove (AB)  

T = B(T)AT  

• Solve the following system of Linear equation using Inverse Methods.  

2x − 3y + z = −1  
x − y + 2z = −3  
3x + y − z = 9  

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}  
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [5]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

inv_A = np.linalg.inv(A)

A_inv_A = np.round(np.matmul(A, inv_A)).astype(int)

print(f'1.\n{A} (A)\n*\n{inv_A} (A inverse)\n=\n{A_inv_A} Identity Matrix\n')

A_B = np.matmul(A, B)
B_A = np.matmul(B, A)

print(f'2.\nAB =\n{A_B}\nBA =\n{B_A}\nAB is not equal to BA\n')

A_Trans = np.transpose(A)
B_Trans = np.transpose(B)
AB_Trans = np.transpose(A_B)
B_Trans_A_Trans = np.matmul(B_Trans, A_Trans)

print(f'3.\n(A * B) transpose =\n{AB_Trans}\nB transpose * A transpose =\n{B_Trans_A_Trans}')
print('(A * B) transpose = B transpose * A transpose\n')

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# Matrix form of above linear equation :
A = np.array([[2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]])
B = np.array([-1, -3, 9])
# Now we have AX = B , where X = [x, y, z]
# Then, X = A-inverse * B
A_inv = np.linalg.inv(A)
A_inv_B = np.matmul(A_inv, B)
# X = A_inv_B
print(f'Using AX = B, the soulution of given system of linear equations is {A_inv_B}.\n')
A_inv_B = np.linalg.solve(A, B)
print(f'Using numpy.linalg.inv, the soulution of given system of linear equations is {A_inv_B}.')




1.
[[3 4]
 [7 8]] (A)
*
[[-2.    1.  ]
 [ 1.75 -0.75]] (A inverse)
=
[[1 0]
 [0 1]] Identity Matrix

2.
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
AB is not equal to BA

3.
(A * B) transpose =
[[23 51]
 [13 29]]
B transpose * A transpose =
[[23 51]
 [13 29]]
(A * B) transpose = B transpose * A transpose

Using AX = B, the soulution of given system of linear equations is [ 2.  1. -2.].

Using numpy.linalg.inv, the soulution of given system of linear equations is [ 2.  1. -2.].


---
4.2 Experiment: How Fast is Numpy?  
In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:  
1. Element-wise Addition:  
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.  
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.  
2. Element-wise Multiplication  
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.  
3. Dot Product  
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.  
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.  
4. Matrix Multiplication  
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.  
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.  

In [8]:
from timeit import timeit

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)


list_addition_time = timeit("[x + y for x, y in zip(list1, list2)]", globals=globals(), number=10)
array_addition_time = timeit("array1 + array2", globals=globals(), number=10)
print(f"Element-wise Addition\nPython lists: {list_addition_time:.4f} sec, NumPy arrays: {array_addition_time:.4f} sec")

list_multiplication_time = timeit("[x * y for x, y in zip(list1, list2)]", globals=globals(), number=10)
array_multiplication_time = timeit("array1 * array2", globals=globals(), number=10)
print(f"Element-wise Multiplication\nPython lists: {list_multiplication_time:.4f} sec, NumPy arrays: {array_multiplication_time:.4f} sec")

list_dot_product_time = timeit("sum(x * y for x, y in zip(list1, list2))", globals=globals(), number= 10)
array_dot_product_time = timeit("np.dot(array1, array2)", globals=globals(), number=10)
print(f"Dot Product\nPython lists: {list_dot_product_time:.4f} sec, NumPy arrays: {array_dot_product_time:.4f} sec")

matrix_size = 1000
# With size 1000, Matrix Multiplication takes
# Python lists: 1865.1110 sec, NumPy arrays: 15.1491 sec

matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

def list_matrix_multiplication(matA, matB):
    """
    Function for cross product of two 2D python lists matA and matB

    Parameters:
        matA : First nested list of AB cross product
        matB : Second nested list of AB cross product
    Returns:
        A python list that is cross product of parameter nested lists
    """
    result = []
    for row in matA:
        row_result = []
        for col in zip(*matB):
            row_result.append(sum(a*b for a, b in zip(row, col)))
        result.append(row_result)
    return result
def array_matrix_multiplication(matA, matB):
    return np.matmul(matA, matB)


list_matrix_multiplication_time = timeit("list_matrix_multiplication(matrix1, matrix2)", globals=globals(), number= 10)
array_matrix_multiplication_time = timeit("array_matrix_multiplication(matrix1, matrix2)", globals=globals(), number=10)

print(f"Matrix Multiplication\nPython lists: {list_matrix_multiplication_time:.4f} sec, NumPy arrays: {array_matrix_multiplication_time:.4f} sec")


Element-wise Addition
Python lists: 0.8669 sec, NumPy arrays: 0.0160 sec
Element-wise Multiplication
Python lists: 0.8983 sec, NumPy arrays: 0.0161 sec
Dot Product
Python lists: 1.0492 sec, NumPy arrays: 0.0120 sec
Matrix Multiplication
Python lists: 1865.1110 sec, NumPy arrays: 15.1491 sec
